# Generated by Django 5.0.6 on 2026-04-14 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('event_type', models.CharField(choices=[('track', '径赛'), ('field', '田赛'), ('fun_individual', '趣味个人'), ('team_confrontation', '对抗团体'), ('relay', '接力团体')], max_length=30, verbose_name='项目类型')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('mixed', '混合')], default='male', max_length=10, verbose_name='参赛性别')),
                ('result_unit', models.CharField(choices=[('second', '秒'), ('meter', '米'), ('count', '次'), ('rank', '名次')], default='second', max_length=20, verbose_name='成绩单位')),
                ('stage_type', models.CharField(choices=[('single', '直接决赛'), ('two', '两阶段(初赛+决赛)'), ('three', '三阶段(初赛+半决赛+决赛)')], default='single', max_length=20, verbose_name='赛制')),
                ('advance_per_group', models.PositiveIntegerField(default=2, verbose_name='每组晋级人数')),
                ('advance_wildcard', models.PositiveIntegerField(default=1, verbose_name='通配名额')),
                ('max_per_class', models.PositiveIntegerField(default=2, verbose_name='每班报名上限')),
                ('max_per_person', models.PositiveIntegerField(default=3, verbose_name='每人最多参加项目数')),
                ('team_size', models.PositiveIntegerField(default=0, verbose_name='每队人数')),
                ('confrontation_format', models.CharField(blank=True, choices=[('bo3', '三局两胜'), ('bo5', '五局三胜')], max_length=10, verbose_name='对抗赛制')),
                ('score_rules', models.JSONField(blank=True, default=dict, verbose_name='积分规则')),
                ('score_multiplier', models.FloatField(default=1.0, verbose_name='积分倍数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_events', to=settings.AUTH_USER_MODEL, verbose_name='负责裁判')),
            ],
            options={
                'verbose_name': '比赛项目',
                'verbose_name_plural': '比赛项目',
                'ordering': ['sports_meet', 'event_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('preliminary', '初赛'), ('semifinal', '半决赛'), ('final', '决赛')], default='final', max_length=20, verbose_name='阶段')),
                ('group_number', models.PositiveIntegerField(default=1, verbose_name='组次')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='比赛时间')),
                ('venue', models.CharField(blank=True, max_length=100, verbose_name='场地')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='events.event', verbose_name='比赛项目')),
            ],
            options={
                'verbose_name': '赛程',
                'verbose_name_plural': '赛程',
                'ordering': ['scheduled_time', 'group_number'],
            },
        ),
        migrations.CreateModel(
            name='SportsMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='运动会名称')),
                ('session', models.PositiveIntegerField(default=1, verbose_name='届次')),
                ('school', models.CharField(blank=True, max_length=100, verbose_name='学校名称')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='报名截止时间')),
                ('status', models.CharField(choices=[('preparing', '筹备中'), ('registration', '报名中'), ('ongoing', '进行中'), ('finished', '已结束')], default='preparing', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '运动会',
                'verbose_name_plural': '运动会',
                'ordering': ['-session'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='sports_meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.sportsmeet', verbose_name='运动会'),
        ),
    ]
