# Generated by Django 3.2.25 on 2026-04-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsmeet',
            name='max_events_per_person',
            field=models.PositiveIntegerField(default=3, verbose_name='每人最多参加项目数'),
        ),
    ]
