# Generated by Django 3.2.25 on 2026-05-11 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_sportsmeet_max_events_per_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sports_meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.sportsmeet', verbose_name='运动会'),
        ),
    ]
