# Generated by Django 3.2.25 on 2026-05-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_sports_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='grade',
            field=models.CharField(blank=True, help_text='留空=全校混赛，填写如2028级=仅限该年级', max_length=20, verbose_name='参赛年级'),
        ),
    ]
