# Generated by Django 5.0.6 on 2026-04-14 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('preliminary', '初赛'), ('semifinal', '半决赛'), ('final', '决赛')], default='final', max_length=20, verbose_name='阶段')),
                ('result', models.CharField(blank=True, max_length=50, verbose_name='成绩')),
                ('result_numeric', models.FloatField(blank=True, null=True, verbose_name='数值成绩')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='名次')),
                ('points', models.FloatField(default=0, verbose_name='积分')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_team_scores', to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
                ('team_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='registration.teamregistration', verbose_name='团体报名')),
            ],
            options={
                'verbose_name': '团体成绩',
                'verbose_name_plural': '团体成绩',
                'unique_together': {('team_registration', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='ConfrontationRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='局次')),
                ('winner_class', models.CharField(max_length=50, verbose_name='胜者班级')),
                ('team_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='scores.teamscore', verbose_name='团体成绩')),
            ],
            options={
                'verbose_name': '对抗局次',
                'verbose_name_plural': '对抗局次',
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='ClassPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级')),
                ('total_points', models.FloatField(default=0, verbose_name='总积分')),
                ('gold_medals', models.PositiveIntegerField(default=0, verbose_name='金牌数')),
                ('silver_medals', models.PositiveIntegerField(default=0, verbose_name='银牌数')),
                ('bronze_medals', models.PositiveIntegerField(default=0, verbose_name='铜牌数')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='排名')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sports_meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_points', to='events.sportsmeet', verbose_name='运动会')),
            ],
            options={
                'verbose_name': '班级积分',
                'verbose_name_plural': '班级积分',
                'ordering': ['-total_points'],
                'unique_together': {('sports_meet', 'class_name')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('preliminary', '初赛'), ('semifinal', '半决赛'), ('final', '决赛')], default='final', max_length=20, verbose_name='阶段')),
                ('result', models.CharField(blank=True, max_length=50, verbose_name='成绩')),
                ('result_numeric', models.FloatField(blank=True, null=True, verbose_name='数值成绩')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='名次')),
                ('points', models.FloatField(default=0, verbose_name='积分')),
                ('is_advanced', models.BooleanField(default=False, verbose_name='是否晋级')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_scores', to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='registration.registration', verbose_name='报名记录')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'ordering': ['rank'],
                'unique_together': {('registration', 'stage')},
            },
        ),
    ]
