# Generated by Django 3.2.25 on 2026-05-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_grade'),
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpoints',
            name='grade',
            field=models.CharField(blank=True, help_text='留空=全校总榜', max_length=20, verbose_name='年级'),
        ),
        migrations.AlterUniqueTogether(
            name='classpoints',
            unique_together={('sports_meet', 'class_name', 'grade')},
        ),
    ]
