# Generated by Django 5.0.6 on 2026-04-14 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级')),
                ('student_id', models.CharField(blank=True, max_length=30, verbose_name='学号')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='年级')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': ['class_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('approved', '已审核'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='submitted', max_length=20, verbose_name='状态')),
                ('lane', models.PositiveIntegerField(blank=True, null=True, verbose_name='道次/顺序')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='比赛项目')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='events.schedule', verbose_name='赛程')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_registrations', to=settings.AUTH_USER_MODEL, verbose_name='报名人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registration.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '报名记录',
                'verbose_name_plural': '报名记录',
                'ordering': ['event', 'lane', 'student__class_name'],
                'unique_together': {('event', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('approved', '已审核'), ('rejected', '已拒绝')], default='submitted', max_length=20, verbose_name='状态')),
                ('lane', models.PositiveIntegerField(blank=True, null=True, verbose_name='道次/顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_registrations', to='events.event', verbose_name='比赛项目')),
                ('members', models.ManyToManyField(blank=True, related_name='team_registrations', to='registration.student', verbose_name='队员')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_participants', to='events.schedule', verbose_name='赛程')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_submitted', to=settings.AUTH_USER_MODEL, verbose_name='报名人')),
            ],
            options={
                'verbose_name': '团体报名',
                'verbose_name_plural': '团体报名',
                'unique_together': {('event', 'class_name')},
            },
        ),
    ]
