# Generated by Django 5.0.6 on 2026-04-14 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('order_book', '秩序册'), ('result_report', '成绩报表')], max_length=20, verbose_name='报告类型')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10, verbose_name='文件格式')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('sports_meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='events.sportsmeet', verbose_name='运动会')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
